services:
  zipkin-collector:
    image: openzipkin/zipkin-slim:latest
    ports:
      - "9411:9411"
    depends_on:
      - otel-collector
    networks:
      - example
  zipkin-client:
    build:
      dockerfile: $PWD/Dockerfile
      context: .
    command:
      - "/bin/sh"
      - "-c"
      - "while ! nc -w 1 -z zipkin-collector 9411; do echo sleep for 1s waiting for zipkin-collector to become available; sleep 1; done && /go/bin/main"
    ports: 
      - "8080:8080"
    networks:
      - example
    depends_on:
      - zipkin-collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.103.1
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    ports:
      - 4318:4318 # OTLP http receiver
    networks:
      - example
networks:
  example:
